### ISSUE TITLE
User authentification fails - implemented ESAE (cross-forest-trust)

### ISSUE THREAD

**Issue by mascr** [lithnet/access-manager#111]
**Describe the bug**
User authentications fails with error
![grafik](https://user-images.githubusercontent.com/87316340/125653247-5bec9483-04fb-4cec-b1df-167d98198764.png)
if user is member of EASE / Admin forest.

**Access Manager installation**
 - OS: Windows Server 2019
 - Version: 1.0.7925.0

**Additional context**
Details about trust:

![grafik](https://user-images.githubusercontent.com/87316340/125653648-03c21c8e-e609-4041-a788-ebe741cfc565.png)

**Logs**
2021-07-14 17:39:48.3133|ERROR|Lithnet.AccessManager.Service.Controllers.ComputerController|The request failed because the information about the authenticated user could not be found
Lithnet.AccessManager.DirectoryException: DsBind failed
 ---> System.ComponentModel.Win32Exception (1355): The specified domain either does not exist or could not be contacted.
   --- End of inner exception stack trace ---
   at Lithnet.AccessManager.DiscoveryServices.FindDcAndExecuteWithRetry[T](String server, String domain, DsGetDcNameFlags flags, DcLocatorMode mode, Func`2 action) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\DiscoveryServices.cs:line 133
   at Lithnet.AccessManager.DiscoveryServices.FindDcAndExecuteWithRetry[T](String domain, DsGetDcNameFlags flags, Func`2 action) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\DiscoveryServices.cs:line 70
   at Lithnet.AccessManager.DiscoveryServices.FindDcAndExecuteWithRetry[T](Func`2 action) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\DiscoveryServices.cs:line 45
   at Lithnet.AccessManager.ActiveDirectory.GetDirectoryEntry(String nameToFind, DsNameFormat nameFormat) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 642
   at Lithnet.AccessManager.ActiveDirectory.GetDirectoryEntry(SecurityIdentifier nameToFind) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 657
   at Lithnet.AccessManager.ActiveDirectory.FindUserInGc(String objectName) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 490
   at Lithnet.AccessManager.ActiveDirectory.GetUser(String name) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 54
   at Lithnet.AccessManager.Service.AppSettings.HttpContextAuthenticationProvider.GetLoggedInUser() in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\HttpContextAuthenticationProvider.cs:line 44
   at Lithnet.AccessManager.Service.Controllers.ComputerController.TryGetUser(IUser& user, IActionResult& failure) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Controllers\ComputerController.cs:line 592

**Comment by ryannewington** [comment]
@mascr 

Just confirming that I have recieve this and can reproduce it. The underlying issue is that AMS is trying to call `DsCrackNames` to convert the logged on users SID, to a directory DN, so it can look up the users details. `DsCrackNames` returns a referral to the red forest, which AMS follows, but subsequently fails, because the AMS server is unable to authenticate to the DC in the red forest to obtain information about the user, due to the one-way trust.

I'll need some time to work through this one, as it's a very complex case.

**Comment by red-erik** [comment]
Hello,
I have same situation, if I can help in any way with some tests, let me know.
Regards,
Red.

**Comment by red-erik** [comment]
Hello,
any news on that ?

Regards,
Red.

**Comment by ryannewington** [comment]
Unfortunately, no progress on this. There hasn't been enough demand from our customers to prioritize ESAE at this stage.

**Comment by red-erik** [comment]
Hello again,
any news on this topic ?

Regards,
Red.

**Comment by ryannewington** [comment]
I don't think we'll be adding support for this scenario sorry @red-erik. We haven't had any customers come out and ask for this and our dev time is spent on customer requests.

The only supported scenario would be to have ESAE users log in to a dedicated instance in the red forest to gain access. 

We don't have a way to resolve the red forest user from the green forest, because the trust fundamentally doesn't allow it. The only way around it would be deploying some sort of proxy inside the red forest that the AMS server can talk to, but that then pokes a hole in the red/green separation.

I'll close this one as not supported, just so it's clear it's not something we plan to add.
