### ISSUE TITLE
Cannot import web.config on server core

### ISSUE THREAD

**Issue by benclaussen1** [lithnet/access-manager#149]
**Describe the bug**
The interface prevents pasting a path to web.config and you cannot browse due to a COM error

**To Reproduce**
1. Install on server core
2. Launch `Lithnet.AccessManager.Server.UI.exe`
3. Select Authorization on the left
4. Select "Import Authorization Rules"
5. Select "Import targets from a Lithnet LAPS web app configuration file" and select Next
6. Select the ellipsis for the file path. Error is generated.

**Expected behavior**
Allow pasting the path in the text field and or use different UI for browsing files

**Screenshots**
![image](https://user-images.githubusercontent.com/46791633/157475337-2cd5b95e-0c19-4167-aac9-bb09ce4ac81f.png)

**Access Manager installation**
 - OS: Windows Server 2022 Datacenter Core
 - Version 2022 Datacenter Core

**Logs**
```
2022-03-09 10:36:42.9059|ERROR|Lithnet.AccessManager.Server.UI.ImportWizardLapsWebSettingsViewModel|Unable to open file
System.Runtime.InteropServices.COMException (0x80040111): Creating an instance of the COM component with CLSID {DC1C5A9C-E88A-4DDE-A5A1-60F82A20AEF7} from the IClassFactory failed due to the following error: 80040111 ClassFactory cannot supply requested class (0x80040111 (CLASS_E_CLASSNOTAVAILABLE)).
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean wrapExceptions, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& hasNoDefaultCtor)
   at System.RuntimeType.CreateInstanceDefaultCtorSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean fillCache)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions)
   at System.Activator.CreateInstance(Type type)
   at Microsoft.Win32.OpenFileDialog.CreateVistaDialog()
   at Microsoft.Win32.FileDialog.RunVistaDialog(IntPtr hwndOwner)
   at Microsoft.Win32.FileDialog.RunDialog(IntPtr hwndOwner)
   at Microsoft.Win32.CommonDialog.ShowDialog(Window owner)
   at Lithnet.AccessManager.Server.UI.ImportWizardLapsWebSettingsViewModel.SelectImportFile() in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server.UI\ViewModels\ImportWizardLapsWebSettingsViewModel.cs:line 110
```

**Comment by ryannewington** [comment]
Hi Ben,

Server core isn't a supported OS, since the configuration app requires a GUI. 

You'll need to use the desktop experience version for this to work.
