### ISSUE TITLE
An error occurred when trying to grant JIT access to an existing group

### ISSUE THREAD

**Issue by s881628** [lithnet/access-manager#15]
**Describe the bug**
Requesting JIT admin access via the web portal for some servers throws the error:
`An error occurred when trying to grant JIT access to DOMAIN\COMPUTER$ for user DOMAIN\USER`
Most servers work as expected, however this one particular server throws the error.  Interestingly, attempting this multiple times on the same server eventually worked as expected without making any changes.
The JIT group exists and the temporary JIT group was created.  The error occurs when trying to add the temporary JIT group to the JIT group.
This is using dynamic groups with a domain functional level of 2012.

**To Reproduce**
1. Turn on automatic JIT group creation
2. Configure the use of dynamic groups
3. Login to web portal and request JIT Admin access to a server
4. You may be returned an error at this point
5. See error

**Expected behavior**
Access should be granted without error

**Access Manager installation**
 - OS: Server 2019 Standard
 - Version 1.0.7596 (and the previous version 1.0.7590)

**Logs**
```
2020-09-03 01:33:42.1387|TRACE|Lithnet.AccessManager.JitAccessProvider|Adding dynamic group DOMAIN\TempJITGroup to the JIT group DOMAIN\JITGroup
2020-09-03 01:33:42.1425|ERROR|Lithnet.AccessManager.Service.Controllers.ComputerController|An error occurred when trying to grant JIT access to DOMAIN\COMPUTER for user DOMAIN\USER
System.DirectoryServices.DirectoryServicesCOMException (0x80072030): There is no such object on the server.
   at System.DirectoryServices.DirectoryEntry.CommitChanges()
   at Lithnet.AccessManager.ActiveDirectoryGroup.AddMember(ISecurityPrincipal principal) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectoryGroup.cs:line 49
   at Lithnet.AccessManager.JitAccessProvider.GrantJitAccessDynamicGroup(IGroup group, IUser user, Boolean canExtend, TimeSpan requestedExpiry, Action& undo) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server\Providers\JitAccessProvider.cs:line 76
   at Lithnet.AccessManager.JitAccessProvider.GrantJitAccess(IGroup group, IUser user, Boolean canExtend, TimeSpan requestedExpiry, Action& undo) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server\Providers\JitAccessProvider.cs:line 35
   at Lithnet.AccessManager.Service.Controllers.ComputerController.GrantJitAccess(AccessRequestModel model, IUser user, IComputer computer, JitAuthorizationResponse authResponse) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Controllers\ComputerController.cs:line 475


```

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.
