### ISSUE TITLE
Issue with reinstall 

### ISSUE THREAD

**Issue by afscme-kmchugh** [lithnet/access-manager#203]
Had to reinstall access manager on same server and now I'm having issues with authentication. Tested windows intergraded and Azure AD. Getting message "Your request could not be processed because your SSO identity could not be found in the directory" Log files have a lot of these messages. 

2023-04-26 13:10:35.1819|TRACE|1164|00-ffd5f44dfad25acd470627f285af5bfa-d87faa6aefc8d9a9-00|172.18.24.12||Lithnet.AccessManager.WebApp.Controllers.HomeController|AuthN error from 172.18.24.12
2023-04-26 13:10:35.2618| INFO|1164|00-ffd5f44dfad25acd470627f285af5bfa-d87faa6aefc8d9a9-00|172.18.24.12||Lithnet.AccessManager.Enterprise.AmsLicenseManager|No license information was found on the system
2023-04-26 13:10:40.4393|TRACE|1164|00-7fefa90e0925cd9f08dac28d7258a59c-608b9977900fefd8-00|172.18.24.12||Lithnet.AccessManager.WebApp.Authentication.OidcAuthenticationProvider|Attempting to find a match in the directory for externally provided claim http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn:user@domain.com
2023-04-26 13:10:40.4473|ERROR|1164|00-7fefa90e0925cd9f08dac28d7258a59c-608b9977900fefd8-00|172.18.24.12||Lithnet.AccessManager.WebApp.Authentication.OidcAuthenticationProvider|There was an exception processing the response from the external identity provider
System.ArgumentNullException: Value cannot be null. (Parameter 'value')
   at System.Security.Claims.Claim..ctor(String type, String value, String valueType, String issuer, String originalIssuer, ClaimsIdentity subject, String propertyKey, String propertyValue)
   at System.Security.Claims.Claim..ctor(String type, String value)
   at Lithnet.AccessManager.WebApp.Authentication.HttpContextAuthenticationProvider.AddAuthZClaims(IActiveDirectoryUser user, ClaimsIdentity identity) in D:\a\1\s\src\Lithnet.AccessManager\Lithnet.AccessManager.WebApp\Authentication\HttpContextAuthenticationProvider.cs:line 22
   at Lithnet.AccessManager.WebApp.Authentication.IdpAuthenticationProvider.FindClaimIdentityInDirectoryOrFailAsync[T](RemoteAuthenticationContext`1 context) in D:\a\1\s\src\Lithnet.AccessManager\Lithnet.AccessManager.WebApp\Authentication\IdpAuthenticationProvider.cs:line 66
2023-04-26 13:10:40.4473|TRACE|1164|00-d66960e8f25c5860a1fdae44d2331469-63f476cacc9f3350-00|172.18.24.12||Lithnet.AccessManager.WebApp.Controllers.HomeController|AuthN error from 172.18.24.12

**Comment by ryannewington** [comment]
@afscme-kmchugh can you confirm you are running the latest version [v2.0.9420](https://packages.lithnet.io/win/access-manager-service/v2.0/x64/LithnetAccessManagerService-2.0.9420.0-x64.exe)? 

Is the Access Manager Service account a member of the `Windows Authorization Access group` in the relevant domains?

This issue is appearing because AMS can't read one of the properties of the user account from AD. Either the msds-PrincipalName or objectSID attributes
