### ISSUE TITLE
Add support for smart card altSecurityIdentities

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#26]
Hello,
I'm not able to authenticate with Smart Card in any possible configuration.
In the log I see:

Lithnet.AccessManager.DirectoryException: DsBind failed
 ---> System.ComponentModel.Win32Exception (1355): The specified domain either does not exist or could not be contacted.
   --- End of inner exception stack trace ---
   at Lithnet.AccessManager.DiscoveryServices.FindDcAndExecuteWithRetry[T](String domain, DsGetDcNameFlags flags, Func`2 action) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\DiscoveryServices.cs:line 93
   at Lithnet.AccessManager.DiscoveryServices.FindDcAndExecuteWithRetry[T](Func`2 action) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\DiscoveryServices.cs:line 29
   at Lithnet.AccessManager.ActiveDirectory.GetDirectoryEntry(String nameToFind, DsNameFormat nameFormat) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 574
   at Lithnet.AccessManager.ActiveDirectory.FindUserInGc(String objectName) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 426
   at Lithnet.AccessManager.ActiveDirectory.GetUser(String name) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 51
   at Lithnet.AccessManager.ActiveDirectory.<>c__DisplayClass7_0.<TryGetUser>b__0() in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 46
   at Lithnet.AccessManager.DirectoryExtensions.TryGet[T](Func`1 getFunc, T& o) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\DirectoryExtensions.cs:line 46
   at Lithnet.AccessManager.ActiveDirectory.TryGetUser(String name, IUser& user) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager\ActiveDirectory\ActiveDirectory.cs:line 46
   at Lithnet.AccessManager.Service.AppSettings.CertificateAuthenticationProvider.ResolveIdentity(CertificateValidatedContext context) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\CertificateAuthenticationProvider.cs:line 159
   at Lithnet.AccessManager.Service.AppSettings.CertificateAuthenticationProvider.<Configure>b__10_1(CertificateValidatedContext context) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\CertificateAuthenticationProvider.cs:line 90

Regards,

Red.

P.S. The CA of my certificates is both on NTAuthStore and on the local server Certification Root Authorities.

**Comment by red-erik** [comment]
Hello,
I believe that AMS is trying to bind with AD looking for UPN and trying to find a Subject Alternative Name into the certificate to match.
If this is the behavior, it's a little bit too restrictive because, for example, no one of us has the UPN in the certificate but we have our email address and RFC822 (in our case, is the same of the email address).
It would be fine to have the possibility to configure attribute matching in a drop down menu, like X509,RFC822, etc.etc. to have more flexibility in SC environment. (Our CA is external from our AD and is not Windows based at all, but present in NTAuthStore).
Otherwise to directly have a match with users' certificates published in AD.

Regards,

Red.

**Comment by ryannewington** [comment]
Hi Red,

You are right it is looking for a SAN containing the UPN.

How are these smartcards mapped to users in the directory in your environment? Using the name mappings (altSecurityIdentities) feature? Or is the cert itself published on their user object?

**Comment by red-erik** [comment]
Hello,
they are mapped with AlsSecurityIdentities and certificates are directly published in AD user object. In AltSecurityIdentities we use RFC822 (in our case correspond to our email address, different from AD UPN).

**Comment by ryannewington** [comment]
Does the altSecurityIdentities attribute contain an `X509` element like `X509:<I>C=US,O=InternetCA,CN=APublicCertificateAuthority<S>C=US,O=Fabrikam,OU=Sales,CN=Jeff Smith`

Are you able to give me an example of someones altSecurityIdentities value?

I'm just trying to get my head around how this works in a multi-forest setup. Usually the UPN is used to determine which forest to route authentication to. If this scenario, how does a user from forest A, log into a service in forest B, without the UPN in the certificate?

**Comment by red-erik** [comment]
Hello,
in AltsecurityIdentities we have a mixture of:
X509:<RFC822>name.surname@emaildomain.com or
X509:<S>O=AAAA,CN=Surname Name,E=name.surname@emaildomain.com,OID.0.9.2342.19200300.100.1.1=S0045438

In our environment we disabled subject alternative name for UPN mapping to have SC working correctly
https://support.microsoft.com/en-us/help/4043463/how-to-disable-the-subject-alternative-name-for-upn-mapping

We don't have the problem because SC are used to logon ONLY in the Forest where the user is defined or on Web application where certificates needs only to be from a trusted source.

**Comment by ryannewington** [comment]
Ok great. That makes sense. 

So if I implement alternate mapping say with email address, it will only be supported for users in the forest where AMS is located (eg we have to be able to find it in our GC). Is that OK for you?

**Comment by red-erik** [comment]
It would be nice to have the possibility to choose but really, for me, is not a constrain to have SC Auth because is it enough to have Integrated Windows Auth. It's only an enhancement that could be useful in complex enterprise environments.

**Comment by ryannewington** [comment]
Microsoft reference implementation

https://docs.microsoft.com/en-us/windows/security/identity-protection/smart-cards/smart-card-certificate-requirements-and-enumeration#kdc-certificate

![image](https://user-images.githubusercontent.com/17229877/92657785-bf371e00-f338-11ea-97bf-75ed6e352494.png)

One notable thing we can't implement is the 'username hint' as the certificate negotiation happens at the TLS layer, and we don't get to participate in that process.

**Comment by red-erik** [comment]
Sure, "username hint" is controlled by Group Policies and in our case (and in all the case I'm aware off) is always disabled.
As said, it would be enough to be able to:
- disable upn mapping search
- select attribute matching (eg. RFC822 -->AltSecurityIdentities)

Red.

**Comment by ryannewington** [comment]
Adds wiki page on how to configure altSecurityIdentity support https://github.com/lithnet/access-manager/wiki/Enabling-AltSecurityIdentities

**Comment by ryannewington** [comment]
This fix is included in [beta-2](https://github.com/lithnet/access-manager/releases/tag/v1.0.7608-beta.2). Please reopen this ticket if there are any issues.

**Comment by red-erik** [comment]
Hello,
the new version with AltSecurityIdentities seems not working. 
With NtAuthStore I receive :
Lithnet.AccessManager.CertificateValidationException: The certificate could not be validated against the NTAuth store. Ensure the issuer is from a trusted enterprise smart-card issuing CA
With Trust any certificate... I receive:
Lithnet.AccessManager.DirectoryException: DsBind failed
---> System.ComponentModel.Win32Exception (1355): The specified domain either does not exist or could not be contacted.

What kind of check AMS is trying to do ?
AuthStore contains ONLY the Issuing CA (as required by Smart Card Logon). Root Ca and Issuing CA are not in my Active Directory but are external and NOT integrated in any AD.

Regards,

Red.
