### ISSUE TITLE
OpenIDConnect provider throws a NullReferenceException on a new configuration file

### ISSUE THREAD

**Issue by dafunky1** [lithnet/access-manager#36]
Getting the following when configured for Azure AD OIDC auth. I'm on the latest build (1.0.7624.0-beta.3).

An unhandled exception has occurred while executing the request.

Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lithnet.AccessManager.Service.AppSettings.OidcAuthenticationProvider.<Configure>b__8_1(OpenIdConnectOptions openIdConnectOptions) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\OidcAuthenticationProvider.cs:line 61
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by ryannewington** [comment]
Hi @dafunky1,

Thanks for reporting this one, this is indeed a bug. 

To get you back up and running ASAP, open the appsettings.config file located at `C:\Program Files\Lithnet\Access Manager Service\config\appsettings.json`, and add in the `Scopes` section as shown below. Just make sure you have the configuration tool closed when you make this change.

```
 "Oidc": {
      "Authority": "https://lithnet.okta.com",
      "ClientID": "12345",
      "ResponseType": "code id_token",
      "ClaimName": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn",
      "IdpLogout": true,
      "Scopes": [
        "profile",
        "openid"
      ]
```

**Comment by dafunky1** [comment]
Closer!
So now I can get passed the Azure signin, but get an error when coming back to the Access Manager portal:
"An authentication error occurred. An unexpected error occurred"
I see the following in the event log:
3000 - "Successfully authenticated and mapped directory user"
52 - "Message contains error: 'invalid_client', error_description: 'AADSTS7000218: The request body must contain the following parameter: 'client_assertion' or 'client_secret'."

**Comment by ryannewington** [comment]
Could you email the manifest from azure ad to me to check what's going on. It's one of the options on the left hand side of the application blade. I'll need to compare it to the one I have here `support@lithnet.io`

There's something wrong with your application setup, but the app registration process has changed since I last did the instructions. I'm trying to work out what setting you need to flip to make this work

**Comment by ryannewington** [comment]
Thanks for sending that through @dafunky1,

I can reproduce the issue on my side now. Let me work on the problem and get back to you

Ryan

**Comment by dafunky1** [comment]
Thank you Ryan! Looking forward to getting this project in lab.

**Comment by ryannewington** [comment]
As a workaround, you can set 

` "ResponseType": "code id_token",`

to 

` "ResponseType": "id_token",`

But I'll provide confirmation on the fix once I've had a bit more time to look into it.

**Comment by dafunky1** [comment]
Now getting the following:
Bad Request - Request Too Long
HTTP Error 400. The size of the request headers is too long.

Tried clearing cookies and Incognito session to no avail. No errors in the event logs.

**Comment by ryannewington** [comment]
I've created a build to resolve this issue. 

https://github.com/lithnet/access-manager/releases/tag/v1.0.7630.0-beta.3.1

Have a look at the release notes, there are a few changes you need to make on the Azure AD side and in your config file (undoing some of the changes we made). 

This moves the application from using implicit flow to authorization code flow, which requires a client secret from Azure. The wiki has been updated with the steps to obtain the secret.

Let me know how you go

**Comment by dafunky1** [comment]
Success!

One thing to note...the configuration UI blanks out the secret field after inputting and saving/restarting, and then will prompt you to re-save the configuration. Effectively, undoing the secret you just inputted. If you just close the UI and do not save, it will keep the secret in the appsettings and will be populated when you open the UI again.

**Comment by ryannewington** [comment]
Yep, ok got this one. Same thing happens with the SMTP password. I'll create a new issue for this, and fix in the next release
