### ISSUE TITLE
You can redirect the config file to a new location be creating a reg key

### ISSUE THREAD

**Issue by dafunky1** [lithnet/access-manager#41]
You can redirect the config file to a new location be creating a reg key

`HKEY_LOCAL_MACHINE\SOFTWARE\Lithnet\Access Manager Service\ConfigPath`

This would allow you to store the config files on the cluster shared volume.

_Originally posted by @ryannewington in https://github.com/lithnet/access-manager/issue_comments/695766226_

When configuring for clustering...the encrypted secrets are not able to be opened on secondary nodes:

ERROR|Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware|An unhandled exception has occurred while executing the request.
Lithnet.AccessManager.ConfigurationException: Unable to decrypt the encrypted data from the configuration file. Use the configuration manager application to re-enter the secret, and try again
 ---> Internal.Cryptography.CryptoThrowHelper+WindowsCryptographicException: Key not valid for use in specified state.
   at System.Security.Cryptography.ProtectedData.ProtectOrUnprotect(Byte[] inputData, Byte[] optionalEntropy, DataProtectionScope scope, Boolean protect)
   at System.Security.Cryptography.ProtectedData.Unprotect(Byte[] encryptedData, Byte[] optionalEntropy, DataProtectionScope scope)
   at Lithnet.AccessManager.Server.Extensions.Extensions.GetSecret(EncryptedData data) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server\Extensions\Extensions.cs:line 85
   --- End of inner exception stack trace ---
   at Lithnet.AccessManager.Server.Extensions.Extensions.GetSecret(EncryptedData data) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server\Extensions\Extensions.cs:line 91
   at Lithnet.AccessManager.Service.AppSettings.OidcAuthenticationProvider.<Configure>b__8_1(OpenIdConnectOptions openIdConnectOptions) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Authentication\OidcAuthenticationProvider.cs:line 49
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass11_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
--- End of stack trace from previous location where exception was thrown ---
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by ryannewington** [comment]
@dafunky1 

Yeah, the clustering scenario turns out to be a bit more complicated than expected. There are issues with Kerberos, secret handling, and rate limit persistence, and there may be others I'm not aware of yet. We do need to do some work to approach this from a different perspective to allow HA scenarios. However, I'm expecting this to fall into the 'enterprise' feature bucket. As a workaround, you can put your secrets in plain text to allow them to load, but just note that clustering is not yet officially supported, and there may be other issues with clustering that need to be solved that I dont have workarounds for at the moment (especially if you are using kerberos auth). The UI might also re-encrypt these values in certain circumstances, so do keep an eye on them. In enterprise edition, clustering will be a first-class citizen.

```
      "Secret": {
        "Data": "xxx",
        "Salt": "xxx",
        "Mode": 1
```

```
      "Secret": {
        "Data": "plain text",
        "Mode": 0
```

**Comment by dafunky1** [comment]
No worries. I will make due with the core product and wait for the enterprise edition. Thanks Ryan
