### ISSUE TITLE
Installer sometimes skips random files, causing deployment issues

### ISSUE THREAD

**Issue by red-erik** [lithnet/access-manager#43]
Hello,
during the upgrade everything was fine but at the end, the flag "Open Access manager.." did not work.
I tried to restart the service and to repair the installation but the Access Manager Configuration did not started (no process running).
After the third repair I was able to start the configuration tool, nothing interesting in the logs.
Windows server 2016 fully patched.
Regards,

Red.

**Comment by ryannewington** [comment]
Hi Red,

Sounds like .NET had a problem starting the app. Can you check the Windows `Application` event log for any error messages from the .NET runtime around the time you were having this problem and provide the details here.

**Comment by red-erik** [comment]
Hello.
first error is:

Application: Lithnet.AccessManager.Service.exe
CoreCLR Version: 4.700.20.36602
.NET Core Version: 3.1.7
Description: The process was terminated due to an unhandled exception.
Exception Info: System.FormatException: Could not parse the JSON file.
 ---> System.Text.Json.JsonReaderException: '{' is invalid after a value. Expected either ',', '}', or ']'. LineNumber: 36 | BytePositionInLine: 3.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenUntilAfterAllCommentsAreSkipped(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextToken(Byte marker)
   at System.Text.Json.Utf8JsonReader.ConsumeNextTokenOrRollback(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationFileParser.ParseStream(Stream input)
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.Configuration.Json.JsonConfigurationProvider.Load(Stream stream)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(ExceptionDispatchInfo info)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Lithnet.AccessManager.Service.Program.<>c.<CreateHostBuilder>b__1_4(IWebHostBuilder webBuilder) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Program.cs:line 71
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.<>c__DisplayClass0_0.<ConfigureWebHostDefaults>b__0(IWebHostBuilder webHostBuilder)
   at Microsoft.Extensions.Hosting.GenericHostWebHostBuilderExtensions.ConfigureWebHost(IHostBuilder builder, Action`1 configure)
   at Microsoft.Extensions.Hosting.GenericHostBuilderExtensions.ConfigureWebHostDefaults(IHostBuilder builder, Action`1 configure)
   at Lithnet.AccessManager.Service.Program.CreateHostBuilder(String[] args) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Program.cs:line 69
   at Lithnet.AccessManager.Service.Program.Main(String[] args) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Service\Program.cs:line 18


second error is:
Description: A .NET Core application failed.
Application: Lithnet.AccessManager.Server.UI.exe
Path: C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Server.UI.exe
Message: The application to execute does not exist: 'C:\Program Files\Lithnet\Access Manager Service\Lithnet.AccessManager.Server.UI.dll'.

Regards,

Red.

**Comment by ryannewington** [comment]
I've seen this happen now as well. There's either an issue with the build process or the installer.

I'm keeping an eye on it.

**Comment by ryannewington** [comment]
Fixed in Beta 4 https://github.com/lithnet/access-manager/releases/tag/v1.0.7846.0-beta.4
