### ISSUE TITLE
Sorting authorization rules crashes AMS if a blank space in title bar is clicked

### ISSUE THREAD

**Issue by jaysnrye** [lithnet/access-manager#61]
**Describe the bug**
When clicking on a blank space in the title bar on the Authorization Rules page, an unhandled exception occurs, crashing AMS.

![image](https://user-images.githubusercontent.com/20349934/101546222-989e8700-39fc-11eb-9aaf-831c6bb665ab.png)

**To Reproduce**
1. Go to the Authorization rules tab
2. Click on a blank space in the auth rules title bar (Next to "Drescription")
3. Observe the crash

**Expected behavior**
Nothing should happen

**Screenshots**

**Access Manager installation**
 - Version 1.0.7856.0

**Logs**
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Lithnet.AccessManager.Server.UI.SecurityDescriptorTargetsViewModel.OnGridViewColumnHeaderClick(Object sender, RoutedEventArgs e) in D:\dev\git\lithnet\access-manager\src\Lithnet.AccessManager\Lithnet.AccessManager.Server.UI\ViewModels\SecurityDescriptorTargetsViewModel.cs:line 391
--- End of stack trace from previous location where exception was thrown ---
   at Stylet.Xaml.ActionBase.InvokeTargetMethod(Object[] parameters) in /_/Stylet/Xaml/ActionBase.cs:line 201
   at Stylet.Xaml.EventAction.InvokeCommand(Object sender, Object e) in /_/Stylet/Xaml/EventAction.cs:line 126
   at Stylet.Xaml.EventAction.InvokeEventArgsCommand(Object sender, EventArgs e) in /_/Stylet/Xaml/EventAction.cs:line 99
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.GridViewColumnHeader.ClickImplement()
   at System.Windows.Controls.GridViewColumnHeader.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.Controls.GridViewColumnHeader.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```

**Comment by ryannewington** [comment]
Fixed in release candidate 1 https://github.com/lithnet/access-manager/releases/tag/v1.0.7872-rc1
